### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by tas509** [Chleba/PIXELARTOR#21]
So if I run yarn start, this all works but if after running yarn dist I try and use the app to export frames (Mac m2 Ventura) I get...

Uncaught Exception:
Error: EROFS: read-only file system, mkdir './data/'
at Object.mkdirSync (fs.js:987:3)
at ExportZip.export (/Users/tas509/Documents/PIXELARTOR/dist/mac-arm64/PIXELARTOR.app/Contents/Resources/app.asar/js/main/export.js:28:38)
at ExportFile._export (/Users/tas509/Documents/PIXELARTOR/dist/mac-arm64/PIXELARTOR.app/Contents/Resources/app.asar/js/main/export.js:82:25)
at IpcMainImpl.emit (events.js:315:20)
at Object.<anonymous> (electron/js2c/browser_init.js:161:9469)
at Object.emit (events.js:315:20)

I gave the app Full Disk access and it still errors.

**Comment by webbrain-one** [comment]
Thanks for the report! I’ve opened #22, which fixes the `EROS: read-only file system` error when exporting frames by using a writable app-data directory instead of trying to create `./data/` inside the packaged app.
